### ISSUE TITLE
Allow changing snippet type

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#136]
![Image](https://github.com/user-attachments/assets/934597e2-8860-415d-8c88-ba6fdebb24cf)

![Image](https://github.com/user-attachments/assets/483a8317-e8e6-484f-b31f-e1f012010201)

**Comment by seveibar** [comment]
Should open a sub-dropdown that allows selecting either "Board" or "Module". The current snippet type should be grayed out

**Comment by ritikpal1122** [comment]
hi assign this to me
