### ISSUE TITLE
Download buttons should work

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#16]
- [x] #17
- [x] #18
- [ ] Download kicad zip should work
- [ ] Download kicad_mod footprint should work

**Comment by imrishabh18** [comment]
@seveibar By download you mean that a `.tsx` file should be downloaded and similarly a `.json` for circuit?

**Comment by seveibar** [comment]
@imrishabh18 thinking about this more, I don't think we should support that as a feature because snippets will eventually be able to have multiple files and people can literally just ctrl-c/cmd-c in the short term. I removed that checklist item

**Comment by imrishabh18** [comment]
Yeah, I thought by download you mean't to download the file. Which is not required as you can copy paste

**Comment by Abse2001** [comment]
@seveibar  Im going to fix this issue to be clear no .tsx file because people can just copy and paste right ?

**Comment by seveibar** [comment]
Yep!
