### ISSUE TITLE
When running locally, automatically load all snippets from `@tscircuit/featured-snippets` module

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#174]
The hardest part of this task is the typescript/javascript has to be compiled. This can be accomplished by importing `CodeRunner` from `@tscircuit/prompt-benchmarks`

You'll also have to compile the typescript to dts, this can also be pretty tricky

You should do this inside a vite plugin when the server first starts IF started in development mode (I don't think we want to start it for every playwright test like this)

If it takes a long time to build, we might want to reconsider our approach and load snippets from production or something using `https://registry-api.tscircuit.com/snippets/list_trending`, we could also have a list of snippets to load in using a txt file.

The point is I want some real-world snippets loaded into snippets when developing- it's better for testing things out

**Comment by ShiboSoftwareDev** [comment]
@seveibar can I instead fetch the snippets from the registry api? I see the featured-snippets repo was not updated for a month

**Comment by seveibar** [comment]
@ShiboSoftwareDev hmm sort of creates an internet dependency when fetching locally- but it's kind of a good idea because we could also "load in problematic snippets". Maybe you could create a txt/json file like "autoload-snippets.json" that is filled with selected snippets, then people can also use it for reproducing issues!!!!!!

**Comment by ShiboSoftwareDev** [comment]
@seveibar  I'll see what I can do

**Comment by ShiboSoftwareDev** [comment]
I can now load selected snippets, should I also load all snippets from here: https://registry-api.tscircuit.com/snippets/list_trending ?

**Comment by seveibar** [comment]
I wouldnt worry about loading trending snippets because youd have to load all their deps and it would be less predictable

**Comment by ShiboSoftwareDev** [comment]
should I also recursively import all snippet's dependencies? 
![Image](https://github.com/user-attachments/assets/cbe5a6c1-488f-40b6-a9d3-371395696cc6)

**Comment by seveibar** [comment]
Oof yea i guess so otherwise it wont work locally….
