### ISSUE TITLE
Fix schematic zooming

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#175]
When you zoom in on the schematic view, it doesn't zoom into the correct location. This most likely requires fixing `use-mouse-matrix-transform` (do not replace it- I don't want to get a bunch of mouse math into this project unnecessarily, but a PR fixing that project is acceptable for the bounty)

In this video I'm scrolling up and down, it SHOULD zoom into the mouse location but instead the screen swings somewhat wildly.

https://github.com/user-attachments/assets/e4627984-ddb9-4f0c-9cc7-996c8d55e45b

**Comment by RohittCodes** [comment]
Hey @seveibar, I would like to work on this. I see the issue is with the `CircuitToSvgWithMouseControl` component, but the actual `Schematic` component isn't stabilized and doesn't have the issue.

So, should I work with the `CircuitToSvgWithMouseControl` component?

**Comment by seveibar** [comment]
The Schematic component is too hard to maintain because it uses a more complex rendering engine, it doesnt have support for rendering circuit json properly, so the fix should be with the CircuitSvgWithMouseControl component
