### ISSUE TITLE
Refreshing the editor page with an unsaved template snippet loads the wrong template on refresh

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#195]
This annoys the hell out of me. If you refresh the page it should re-use the same template. One way to resolve this is to make sure when we open an unsaved snippet we keep the template type in the url

https://github.com/user-attachments/assets/5d2ff280-8215-4cba-9db1-97fc46aa022a

/bounty $8

**Comment by developerfred** [comment]
/attempt #195 

I will update CodeEditor
 
- Adding template state tracking using a URL query parameter
- Preserving the template type across page refreshes
- Loading the correct template content based on the URL parameter
