### ISSUE TITLE
Add support for unstarring a snippet

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#197]
Sometimes we want to unstar things instead of starring them

![Image](https://github.com/user-attachments/assets/90a496ba-d343-407d-9466-7f44a70d3b2b)

Note that the api is supposed to return `snippet.is_starred` to indicate that the current user starred the snippet

**Comment by RohittCodes** [comment]
should i create another route for it? the initial one would be good enough to handle the add, and remove logic if it's not starred. like toggle the button to star and remove the star.

and it may not need much work on the frontend too. @seveibar
