### ISSUE TITLE
As the snippets gets more star it duplicates on the dashboard

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#200]
![Image](https://github.com/user-attachments/assets/2bb5f94b-4cb0-446d-9be8-c5566b76e5eb)

The `motor-driver-breakout` appears twice on the list

cc: @seveibar

**Comment by ahmedhalac** [comment]
is this list of snippets hardcoded?

**Comment by imrishabh18** [comment]
@ahmedhalac No, the trending snippets list is not hardcoded

**Comment by Abse2001** [comment]
@imrishabh18 I can't repro in local
 ![Image](https://github.com/user-attachments/assets/0e1802c3-a24c-421d-8c60-4edc7f0214f2)

**Comment by imrishabh18** [comment]
@Abse2001 It is still getting duplicated as you can test in the https://tscircuit.com

**Comment by Abse2001** [comment]
@imrishabh18 ya I was asking if you now if we can repro in local.

**Comment by Abse2001** [comment]
when you are signed out there is no duplicate  https://tscircuit.com 
![Image](https://github.com/user-attachments/assets/19f65504-9290-48c2-8cb1-faad98925742)
when signed in there is.
![Image](https://github.com/user-attachments/assets/79a2f0a0-3b65-44d9-90ab-2d8857ceec33)

**Comment by Abse2001** [comment]
@seveibar on local repo it does not get duplicated either if you are signed in or not idk how to repro this one.

**Comment by imrishabh18** [comment]
Even I am not sure, probably it's a production api issue

**Comment by seveibar** [comment]
@imrishabh18 yep it's a production API issue, @Abse2001 has figured out it's related to a join with user data because of the auth token

Internal issue w/ prod api filed here: https://github.com/tscircuit/registry-api/issues/36

Inside `getSnippetsQuery` function used here https://github.com/tscircuit/registry-api/blob/main/routes/snippets/list_trending.ts
