### ISSUE TITLE
Schematic view is a bit chopped off from the top and bottom

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#207]
https://tscircuit.com/editor?snippet_id=d2c1c529-97b0-41de-96fa-2cc0c84ba342

![Image](https://github.com/user-attachments/assets/1247715a-3027-4b38-9ffe-5c8d0d44bbf9)

The traces on the top and bottom are incomplete and cut off.

**Comment by seveibar** [comment]
@imrishabh18 i think this is fixed in the most recent version of circuit-to-svg, i fixed a bug where schematic trace wasn't being taken into account for bounds calculation

**Comment by seveibar** [comment]
@imrishabh18 ok update: it never made it in, i'll do a PR now

**Comment by seveibar** [comment]
Fixed in circuit-to-svg in this PR: https://github.com/tscircuit/circuit-to-svg/pull/126
