### ISSUE TITLE
When you run after a React syntax error, give a good syntax error message in the errors panel

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#215]
![Image](https://github.com/user-attachments/assets/7dcdeb0a-c724-4f78-befd-952d693f4441)

Maybe babel can help us get a good syntax error, not sure.

/bounty $15

**Comment by kom-senapati** [comment]
/attempt #215

Creating an util at `src/lib/utils/getSyntaxError.ts` which checks the code and gives syntax errors by using babel
Using this util at `src/hooks/use-run-tsx/index.tsx` to return error as message
