### ISSUE TITLE
The chip 3D view is missing the chip (regression)

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#222]
https://tscircuit.com/imrishabh18/motor-driver-breakout

The 3D view is missing the chip, while it was present before.

![Image](https://github.com/user-attachments/assets/f0d84666-8e33-4d55-b424-785354431859)

**Comment by seveibar** [comment]
@imrishabh18 is it a jlcpcb chip? This is likely because of an unavoidable CORS error when we use both snippets.tscircuit.com and tscircuit.com. To fix it, we have to add a url parameter that includes the domain to "bash the cache"

**Comment by seveibar** [comment]
In effect, this means the fix has to be in core. Basically in `3d viewer` or `jscad-electronics` we need to append the domain as a query parameter whenever we request a model from the model cdn. It doesn't matter if the model cdn accepts the parameter or not- it's just to trick the browser into bashing the cache.

e.g. `modelcdn.tscircuit.com?.....&origin=snippet.tscircuit.com`

**Comment by imrishabh18** [comment]
@seveibar The error is not consistent, when I open the chip 3d view here - https://tscircuit.com/imrishabh18/TB6612FNG. I can see the chip rendering file.
But now the 3d view is failing for the motor-driver - https://tscircuit.com/imrishabh18/motor-driver-breakout

**Comment by imrishabh18** [comment]
@Anshgrover23 Yeah, the errors in the 3d viewer are not consistent. The `jscad-fiber` version when updated in 3d-viewer was breaking the view. Cause the `createJSCADRenderer` in fiber is modifying the structure of jscadPlan.

I will create an issue in the `jscad-fiber` about this, if you want to take a look and tackle this. It would be great

**Comment by imrishabh18** [comment]
https://github.com/tscircuit/jscad-fiber/issues/92

Take a look @Anshgrover23. I have added some of my findings while debugging
