### ISSUE TITLE
Edit snippet name

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#24]
Currently, all the snippets are having the same `untitled` name and no option to edit it

**Comment by PALLAVIKHEDLE** [comment]
@imrishabh18 Can you please assign it to me?  I will finish it quickly.

**Comment by imrishabh18** [comment]
Sure! Thanks for picking this up

**Comment by PALLAVIKHEDLE** [comment]
@imrishabh18  - Do you mind running through the steps on how to create snippets? I am not able to create one/reproduce the use-case. Thanks!

**Comment by imrishabh18** [comment]
As you can see in the video, that there is no option to edit the name `untitled-board-3` snippet. Probably one should be able to edit the name of the snippet they have. Somewhat like a pencil icon on the side of the name, to enable edit.

cc: @seveibar 

https://github.com/user-attachments/assets/c27ce3bc-6fb9-433b-a659-ebb0a28e34a8

**Comment by PALLAVIKHEDLE** [comment]
Thank you so much! I will make changes and submit it for review in morning!

**Comment by PALLAVIKHEDLE** [comment]
![Image](https://github.com/user-attachments/assets/f71b8031-d50c-4fd3-ad8d-c1f296c0dbeb)
I am not able to generate a code. API Failed.

**Comment by seveibar** [comment]
@PALLAVIKHEDLE this is fixed on the `/editor` page if you pull main. To use AI, you have to follow the instructions in the README to get an ANTHROPIC_API_KEY, reach out to me on discord if you need one

**Comment by PALLAVIKHEDLE** [comment]
Thanks for getting back to me! 
I need an API key, 'pallavi3014' this is my discord ID. I am sorry not able to join you on discord.

**Comment by PALLAVIKHEDLE** [comment]
@seveibar, can you please provide an API key?

**Comment by seveibar** [comment]
@PALLAVIKHEDLE you can join the discord at this link, DM me there: https://tscircuit.com/join

**Comment by seveibar** [comment]
This is now fixed via the editor page #57
