### ISSUE TITLE
Mobile view Is broken

### ISSUE THREAD

**Issue by valentimarco** [tscircuit/snippets#25]
When opening the site on mobile, the view Is broken!
A list of issues:
1. The size of the Page Is actually this but only of you zoom out (i am not in desktop mode, as brave calls)
![IMG_20241006_152543.jpg](https://github.com/user-attachments/assets/76107ac1-ef30-4ebf-b5a8-ab9c4f66b765)

2. View when opening the First time:
![IMG_20241006_152800.jpg](https://github.com/user-attachments/assets/9f519d32-0ddd-4fbf-ad43-5695858e7583)

3. Text overflow in buttons:
![IMG_20241006_153049.jpg](https://github.com/user-attachments/assets/c937c50e-5f2c-4cd4-8a9f-d941c98bf99b)
![IMG_20241006_153150.jpg](https://github.com/user-attachments/assets/31beceb6-b2e0-4e9b-ab66-cbb1d7d9700d)

4. List of trending out of screen and Page size much bigger than screen size
![IMG_20241006_153219.jpg](https://github.com/user-attachments/assets/17f54e11-5f77-48ca-92ee-9a5df59e49d5)

**Comment by seveibar** [comment]
Great issue, totally agree we need to fix this!

**Comment by DhairyaMajmudar** [comment]
@seveibar would love to take on this can you pls. assign

**Comment by seveibar** [comment]
because this issue is ELITE (chance of failure is high) we won't assign, but feel free to go for it, we just don't want someone to grab it and not finish

**Comment by seveibar** [comment]
@DhairyaMajmudar fwiw you could break this into sub-issues that are assignable

**Comment by DhairyaMajmudar** [comment]
> [@DhairyaMajmudar](https://github.com/DhairyaMajmudar) fwiw you could break this into sub-issues that are assignable

Yup, much better

**Comment by PALLAVIKHEDLE** [comment]
@seveibar Can you please assign it to me? I will finish it quickly.
