### ISSUE TITLE
`EidtorNav.tsx` mobile ui overflowing

### ISSUE THREAD

**Issue by Abse2001** [tscircuit/snippets#284]
Try make it more responsive and maybe try to use another design for the `unsaved ` for mobile.
![IMG_20241125_130047_390.jpg](https://github.com/user-attachments/assets/c68ffc38-858e-44c1-9810-b9c6353c1c28)

![IMG_20241125_130050_425.jpg](https://github.com/user-attachments/assets/1e93462c-d84b-4344-bef0-39d83f094730)

**Comment by imrishabh18** [comment]
https://github.com/user-attachments/assets/dc77b556-84f1-40f2-97c7-74b603f80bc0

Can you guys please confirm this has been fixed? Cause I can't see this responsive. Is it a issue on my mobile end 🤔

Cc: @anas-sarkez @Abse2001

**Comment by anas-sarkez** [comment]
I've fixed the editor page.
I think its another issue 
![image](https://github.com/user-attachments/assets/fed18aab-8c9f-4d08-81e9-2c250f1a24b2)
![image](https://github.com/user-attachments/assets/35b62f0c-4a0c-4d77-9fee-3fd050632e17)

**Comment by imrishabh18** [comment]
Not sure know about the redesign of the mobile view,but I think we can create a issue which lists all these small responsive fixes here and there for mobile view. And I can add a bounty to it

**Comment by Abse2001** [comment]
@ imrishabh18 You are right that a redesign is not a top priority.
I will open issues for any bugs I encounter.
