### ISSUE TITLE
Multiple lock files in codebase

### ISSUE THREAD

**Issue by DhairyaMajmudar** [tscircuit/snippets#3]
-> There are two lockfiles in the project codebase which are `package-lock.json` generated due to npm and `bun.lockb` generated due to bun

-> Having these two different lock files in the codebase causes PacakgeManager related issues so deleting one of them would be good to go
 
-> ScreenShot from VSCode 

![image](https://github.com/user-attachments/assets/f76a444c-46ec-4f34-9e13-fce328ad284c)

**Comment by DhairyaMajmudar** [comment]
POV: Removing package-lock.json would be a good decision to be taken reason being bun is faster in installing dependencies as compared to npm 

What's your POV on this @seveibar ?

**Comment by imrishabh18** [comment]
@DhairyaMajmudar Good point! Yes, we can remove the `package-lock` file. I see @Complexlity has raised a PR for it as well.

Thanks for pointing this out
