### ISSUE TITLE
Hovering over the "New" button should open the dropdown, pressing the "New" button should go to "/editor"

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#30]
This will allow people to select from all the templates available on the "/editor" page

**Comment by PALLAVIKHEDLE** [comment]
@seveibar Can you please assign this to me? It looks interesting. I can easily knock this out.

**Comment by PALLAVIKHEDLE** [comment]
Thanks so much for assigning it to me. 
I have just submitted the PR. Can you please review it whenever you get a chance? Thanks!
