### ISSUE TITLE
Cmd Click is broken for clicking on snippets

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#313]
There is no underline and you can't click on it

![Image](https://github.com/user-attachments/assets/68ee84c0-8e11-4082-993c-b69e05176c1a)

**Comment by seveibar** [comment]
Likely broken in https://github.com/tscircuit/snippets/pull/302 CC @Anshgrover23

**Comment by seveibar** [comment]
@Anshgrover23 you can't click on it to go to the snippet. It used to be underlined and you could click on it, that was the main functionality that the regex was there for.

**Comment by seveibar** [comment]
@Anshgrover23 this is still not fixed, look at this snippet: https://tscircuit.com/editor?snippet_id=48b2b687-2e72-4d2e-8a1e-5afafb0b11ba

**Comment by Anshgrover23** [comment]
@seveibar The regex has a static part `@tsci/` and the issue that you are saying `@tscircuit/core` .
The earlier version of REGEX which you were using would also not work on this one too.

**Comment by Anshgrover23** [comment]
Asking is there a snippet written for `@tscircuit/core` ?

**Comment by seveibar** [comment]
@Anshgrover23 ![Image](https://github.com/user-attachments/assets/b2e05990-a692-4562-bcd7-d52bef799fd5)

**Comment by seveibar** [comment]
you can also click on the snippet on line 2, it doesn't work

**Comment by seveibar** [comment]
even looking at the underline, it's not underlining the entire snippet
