### ISSUE TITLE
Arduino Nano Servo Breakout

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/snippets#337]

**Comment by ShiboSoftwareDev** [comment]
requires arduino nano

**Comment by ShiboSoftwareDev** [comment]
https://www.pcbway.com/project/shareproject/PCB_for_Robotic_Arm_de9257b3.html we found a simple board, it gets the job done

**Comment by seveibar** [comment]
Recommending we rename to "Arduino Nano Servo Breakout"
