### ISSUE TITLE
Improve error message of the already imported jlcpcb part

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/snippets#427]
The error message is coming from the https://github.com/tscircuit/easyeda-converter, we can modify there and some parts of the message here to convey better message for this case

![Image](https://github.com/user-attachments/assets/4fa5abb4-1186-4fc3-a54c-2beb8cbd7956)

The error message needs to improve when that component is already imported

**Comment by seveibar** [comment]
this is a server-side issue: https://github.com/tscircuit/registry-api/issues/102
