### ISSUE TITLE
Orders page

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#44]
We want to eventually allow ordering circuit boards from tscircuit snippets, so this issue tracks all the stuff to make that happen.

Note that the orders api backend isn't open-source because it contains code from our integration partners that is locked down, but the fake version is open-source, as well as the ordering interface.

- [x] Orders and order files schema
- [x] `/orders/*` and `/order_files/*` fake endpoints
- [x] My orders page `/my-orders`
- [x] Add header option to see orders by clicking your profile picture
- [ ] View order page `/orders/{order_id}`
- [ ] New order page `/new-order`

Use AI to generate the pages and be relatively descriptive about the contents, it'll generate something decent if you add the api into the context `/add src fake-snippets-api`

**Comment by andrii-balitskyi** [comment]
Some of the items were implemented in https://github.com/tscircuit/snippets/pull/46
