### ISSUE TITLE
Make "New" dropdown work

### ISSUE THREAD

**Issue by seveibar** [tscircuit/snippets#7]
![image](https://github.com/user-attachments/assets/a24c26e6-c26c-4346-8dee-122c0b953b46)

![image](https://github.com/user-attachments/assets/8363a82e-94c3-47d9-8c1e-d3ee7fc6f5b7)

**Comment by DhairyaMajmudar** [comment]
@seveibar I would like to take this up can you pls. assign

**Comment by seveibar** [comment]
@DhairyaMajmudar @Complexlity just nabbed this. Issues can go fast!!!! There are many other issues available if you just click around the UI it's very broken

**Comment by DhairyaMajmudar** [comment]
> [@DhairyaMajmudar](https://github.com/DhairyaMajmudar) [@Complexlity](https://github.com/Complexlity) just nabbed this. Issues can go fast!!!! There are many other issues available if you just click around the UI it's very broken

@Complexlity super fast man! NW I'll look of other things : )
